### ISSUE TITLE
This is now working...

### ISSUE THREAD

**Issue by NateRickard** [LifeCoder45/MissingVectorDrawableCompat#1]
Sorry for the non-issue issue, but just wanted to drop you a note as I came across your repo while messing with this.  As of 23.2.1-beta1 the `app:srcCompat` can be used properly.

See example here: https://github.com/NateRickard/AndroidAppCompatVectorDrawables

**Comment by ggirard07** [comment]
Did you manage to get this to work on pre lollipop devices? Currently getting an `Android.Content.Res.Resources+NotFoundException: File res/drawable/mydrawable.xml from drawable resource ID #0x7f020079`...

Also, still don't know if `vectorDrawables.useSupportLibrary = true` graddle config is applicable anywhere when working witg Xamarin...
